import { EGlob } from "../constants/glob";

import type { IConfig } from "../types/config";

export function javascriptConfig(): IConfig[] {
  return [
    {
      name: "wondermarin/eslint-config/javascript",
      files: [EGlob.JS, EGlob.JSX, EGlob.TS, EGlob.TSX, EGlob.VUE],
      rules: {
        "accessor-pairs": [
          "error",
          {
            enforceForClassMembers: true,
            getWithoutSet: false,
            setWithoutGet: true,
          },
        ],
        "array-callback-return": [
          "error",
          {
            allowImplicit: false,
            allowVoid: false,
            checkForEach: false,
          },
        ],
        "arrow-body-style": ["error", "as-needed", { requireReturnForObjectLiteral: false }],
        "block-scoped-var": "error",
        camelcase: [
          "error",
          {
            ignoreDestructuring: false,
            ignoreGlobals: false,
            ignoreImports: false,
            properties: "never",
          },
        ],
        "capitalized-comments": "off",
        "class-methods-use-this": "off",
        complexity: "off",
        "consistent-return": "off",
        "consistent-this": "off",
        "constructor-super": "error",
        curly: "off",
        "default-case": "error",
        "default-case-last": "error",
        "default-param-last": "error",
        "dot-notation": ["error", { allowKeywords: true }],
        eqeqeq: ["error", "always"],
        "for-direction": "error",
        "func-name-matching": "off",
        "func-names": ["error", "as-needed"],
        "func-style": ["error", "declaration", { allowArrowFunctions: true }],
        "getter-return": ["error", { allowImplicit: false }],
        "grouped-accessor-pairs": ["error", "getBeforeSet"],
        "guard-for-in": "off",
        "id-denylist": "off",
        "id-length": "off",
        "id-match": "off",
        "init-declarations": "off",
        "logical-assignment-operators": ["error", "always", { enforceForIfStatements: true }],
        "max-classes-per-file": [
          "error",
          {
            ignoreExpressions: false,
            max: 1,
          },
        ],
        "max-depth": "off",
        "max-lines": "off",
        "max-lines-per-function": "off",
        "max-nested-callbacks": "off",
        "max-params": "off",
        "max-statements": "off",
        "new-cap": [
          "error",
          {
            capIsNew: false,
            newIsCap: true,
            properties: false,
          },
        ],
        "no-alert": "error",
        "no-array-constructor": "error",
        "no-async-promise-executor": "error",
        "no-await-in-loop": "off",
        "no-bitwise": "off",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": ["error", "always"],
        "no-console": "off",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": ["error", { checkLoops: true }],
        "no-constructor-return": "error",
        "no-continue": "off",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-div-regex": "error",
        "no-dupe-args": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-duplicate-imports": ["error", { includeExports: true }],
        "no-else-return": ["error", { allowElseIf: false }],
        "no-empty": ["error", { allowEmptyCatch: true }],
        "no-empty-character-class": "error",
        "no-empty-function": "error",
        "no-empty-pattern": ["error", { allowObjectPatternsAsParameters: false }],
        "no-empty-static-block": "error",
        "no-eq-null": "error",
        "no-eval": ["error", { allowIndirect: false }],
        "no-ex-assign": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-boolean-cast": ["error", { enforceForInnerExpressions: false }],
        "no-extra-label": "error",
        "no-fallthrough": ["error", { allowEmptyCase: true }],
        "no-func-assign": "error",
        "no-global-assign": "error",
        "no-implicit-coercion": "off",
        "no-implicit-globals": "off",
        "no-implied-eval": "error",
        "no-import-assign": "error",
        "no-inline-comments": "error",
        "no-inner-declarations": ["error", "functions"],
        "no-invalid-regexp": "error",
        "no-invalid-this": ["error", { capIsConstructor: true }],
        "no-irregular-whitespace": [
          "error",
          {
            skipComments: false,
            skipJSXText: false,
            skipRegExps: false,
            skipStrings: true,
            skipTemplates: true,
          },
        ],
        "no-iterator": "error",
        "no-label-var": "error",
        "no-labels": [
          "error",
          {
            allowLoop: false,
            allowSwitch: false,
          },
        ],
        "no-lone-blocks": "error",
        "no-lonely-if": "off",
        "no-loop-func": "error",
        "no-loss-of-precision": "error",
        "no-magic-numbers": "off",
        "no-misleading-character-class": ["error", { allowEscape: false }],
        "no-multi-assign": ["error", { ignoreNonDeclaration: false }],
        "no-multi-str": "error",
        "no-negated-condition": "error",
        "no-nested-ternary": "off",
        "no-new": "error",
        "no-new-func": "error",
        "no-new-native-nonconstructor": "error",
        "no-new-wrappers": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "error",
        "no-object-constructor": "error",
        "no-octal": "error",
        "no-octal-escape": "error",
        "no-param-reassign": "off",
        "no-plusplus": "off",
        "no-promise-executor-return": ["error", { allowVoid: false }],
        "no-proto": "error",
        "no-prototype-builtins": "error",
        "no-redeclare": ["error", { builtinGlobals: true }],
        "no-regex-spaces": "error",
        "no-restricted-exports": "off",
        "no-restricted-globals": "off",
        "no-restricted-imports": "off",
        "no-restricted-properties": "off",
        "no-restricted-syntax": "off",
        "no-return-assign": ["error", "except-parens"],
        "no-script-url": "error",
        "no-self-assign": ["error", { props: true }],
        "no-self-compare": "error",
        "no-sequences": ["error", { allowInParentheses: true }],
        "no-setter-return": "error",
        "no-shadow": "off",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-template-curly-in-string": "error",
        "no-ternary": "off",
        "no-this-before-super": "error",
        "no-throw-literal": "error",
        "no-undef": ["error", { typeof: false }],
        "no-undef-init": "error",
        "no-undefined": "off",
        "no-underscore-dangle": [
          "error",
          {
            allowAfterSuper: false,
            allowAfterThis: false,
            allowAfterThisConstructor: false,
            allowFunctionParams: false,
            allowInArrayDestructuring: false,
            allowInObjectDestructuring: false,
            enforceInClassFields: false,
            enforceInMethodNames: false,
          },
        ],
        "no-unexpected-multiline": "error",
        "no-unmodified-loop-condition": "error",
        "no-unneeded-ternary": ["error", { defaultAssignment: false }],
        "no-unreachable": "error",
        "no-unreachable-loop": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
        "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
        "no-unused-expressions": [
          "error",
          {
            allowShortCircuit: false,
            allowTaggedTemplates: false,
            allowTernary: false,
            enforceForJSX: false,
          },
        ],
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": [
          "error",
          {
            args: "after-used",
            caughtErrors: "all",
            ignoreRestSiblings: true,
            vars: "all",
          },
        ],
        "no-use-before-define": [
          "error",
          {
            allowNamedExports: false,
            classes: true,
            functions: true,
            variables: true,
          },
        ],
        "no-useless-assignment": "error",
        "no-useless-backreference": "error",
        "no-useless-call": "error",
        "no-useless-catch": "error",
        "no-useless-computed-key": ["error", { enforceForClassMembers: true }],
        "no-useless-concat": "error",
        "no-useless-constructor": "error",
        "no-useless-escape": "error",
        "no-useless-rename": [
          "error",
          {
            ignoreDestructuring: false,
            ignoreExport: false,
            ignoreImport: false,
          },
        ],
        "no-useless-return": "error",
        "no-var": "error",
        "no-void": ["error", { allowAsStatement: true }],
        "no-warning-comments": "off",
        "no-with": "error",
        "object-shorthand": [
          "error",
          "always",
          {
            avoidExplicitReturnArrows: false,
            avoidQuotes: false,
            ignoreConstructors: false,
          },
        ],
        "one-var": ["error", "never"],
        "operator-assignment": ["error", "always"],
        "prefer-arrow-callback": [
          "error",
          {
            allowNamedFunctions: false,
            allowUnboundThis: false,
          },
        ],
        "prefer-const": [
          "error",
          {
            destructuring: "all",
            ignoreReadBeforeAssign: false,
          },
        ],
        "prefer-destructuring": [
          "error",
          {
            array: true,
            object: true,
          },
          {
            enforceForRenamedProperties: false,
          },
        ],
        "prefer-exponentiation-operator": "error",
        "prefer-named-capture-group": "off",
        "prefer-numeric-literals": "off",
        "prefer-object-has-own": "error",
        "prefer-object-spread": "error",
        "prefer-promise-reject-errors": "off",
        "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
        "prefer-rest-params": "error",
        "prefer-spread": "error",
        "prefer-template": "error",
        radix: ["error", "always"],
        "require-atomic-updates": ["error", { allowProperties: false }],
        "require-await": "error",
        "require-unicode-regexp": ["error", { requireFlag: "v" }],
        "require-yield": "error",
        "sort-imports": "off",
        "sort-keys": "off",
        "sort-vars": "off",
        strict: ["error", "never"],
        "symbol-description": "error",
        "unicode-bom": ["error", "never"],
        "use-isnan": [
          "error",
          {
            enforceForIndexOf: true,
            enforceForSwitchCase: true,
          },
        ],
        "valid-typeof": ["error", { requireStringLiterals: true }],
        "vars-on-top": "error",
        yoda: [
          "error",
          "never",
          {
            exceptRange: false,
            onlyEquality: false,
          },
        ],
      },
    },
  ];
}
